export const routes = [ 
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Plane', title: 'Complex Plane' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Division-of-Complex-Numbers', title: 'Division of Complex Numbers' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Polar-form', title: 'Polar form' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Argand-Diagrams', title: 'Argand Diagrams' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Numbers-intro', title: 'Complex Numbers intro' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2', title: 'ComplexNumbers A2' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Numbers-A2', title: 'Complex Numbers A2' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Exponents', title: 'Complex Exponents' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-inverse-tangent', title: 'Differentiating inverse tangent' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-trigonometric-functions', title: 'Differentiating trigonometric functions' },
 { path: '/A2-Math-Pure/Calculus-A2/Differential-Equations', title: 'Differential Equations' },
 { path: '/A2-Math-Pure/Calculus-A2/Implicit-Differentiation', title: 'Implicit Differentiation' },
 { path: '/A2-Math-Pure/Calculus-A2/Calculus-A2', title: 'Calculus A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-A2', title: 'Integration A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Quotient-Rule', title: 'Quotient Rule' },
 { path: '/A2-Math-Pure/Calculus-A2/U---substitution', title: 'U   substitution' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-natural-logs-and-exponentials', title: 'Differentiating natural logs and exponentials' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-Rules-A2', title: 'Integration Rules A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Reverse-Chain-Rule-A2', title: 'Reverse Chain Rule A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-by-parts', title: 'Integration by parts' },
 { path: '/A2-Math-Pure/Calculus-A2/Parametric-Equations', title: 'Parametric Equations' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiation-A2', title: 'Differentiation A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiation-Rules-A2', title: 'Differentiation Rules A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Product-Rule', title: 'Product Rule' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Double-Angles', title: 'Double Angles' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Compound-Angles', title: 'Compound Angles' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Reciprocal-Trigonometry-Functions', title: 'Reciprocal Trigonometry Functions' },
 { path: '/A2-Math-Pure/Trigonometry-A2/R---Method', title: 'R   Method' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Trigonometry-A2', title: 'Trigonometry A2' },
 { path: '/A2-Math-Pure/Numerical-Methods', title: 'Numerical Methods' },
 { path: '/A2-Math-Pure/Partial-Fractions', title: 'Partial Fractions' },
 { path: '/A2-Math-Pure/Binomial-Expansion-A2', title: 'Binomial Expansion A2' },
 { path: '/A2-Math-Pure/Euler\'s-Number', title: 'Euler\'s Number' },
 { path: '/A2-Math-Pure/Dot-Product', title: 'Dot Product' },
 { path: '/A2-Math-Pure/Modelling-Curves', title: 'Modelling Curves' },
 { path: '/A2-Math-Pure/Exponential-Graphs', title: 'Exponential Graphs' },
 { path: '/A2-Math-Pure/Logs', title: 'Logs' },
 { path: '/A2-Math-Pure/Factorization', title: 'Factorization' },
 { path: '/A2-Math-Pure/Remainder-Theorem', title: 'Remainder Theorem' },
 { path: '/A2-Math-Pure/Vectors-A2', title: 'Vectors A2' },
 { path: '/A2-Math-Pure/Absolute-Value-Equations', title: 'Absolute Value Equations' },
];

