export const routes = [ 
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Plane', title: 'Complex Plane' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Division-of-Complex-Numbers', title: 'Division of Complex Numbers' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Polar-form', title: 'Polar form' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Argand-Diagrams', title: 'Argand Diagrams' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Numbers-intro', title: 'Complex Numbers intro' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2', title: 'ComplexNumbers A2' },
 { path: '/A2-Math-Pure/ComplexNumbers-A2/Complex-Exponents', title: 'Complex Exponents' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-inverse-tangent', title: 'Differentiating inverse tangent' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-trigonometric-functions', title: 'Differentiating trigonometric functions' },
 { path: '/A2-Math-Pure/Calculus-A2/Differential-Equations', title: 'Differential Equations' },
 { path: '/A2-Math-Pure/Calculus-A2/Implicit-Differentiation', title: 'Implicit Differentiation' },
 { path: '/A2-Math-Pure/Calculus-A2/Calculus-A2', title: 'Calculus A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-A2', title: 'Integration A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Quotient-Rule', title: 'Quotient Rule' },
 { path: '/A2-Math-Pure/Calculus-A2/U---substitution', title: 'U   substitution' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiating-natural-logs-and-exponentials', title: 'Differentiating natural logs and exponentials' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-Rules-A2', title: 'Integration Rules A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Reverse-Chain-Rule-A2', title: 'Reverse Chain Rule A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Integration-by-parts', title: 'Integration by parts' },
 { path: '/A2-Math-Pure/Calculus-A2/Parametric-Equations', title: 'Parametric Equations' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiation-A2', title: 'Differentiation A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Differentiation-Rules-A2', title: 'Differentiation Rules A2' },
 { path: '/A2-Math-Pure/Calculus-A2/Product-Rule', title: 'Product Rule' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Double-Angles', title: 'Double Angles' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Compound-Angles', title: 'Compound Angles' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Reciprocal-Trigonometry-Functions', title: 'Reciprocal Trigonometry Functions' },
 { path: '/A2-Math-Pure/Trigonometry-A2/R-Method', title: 'R-Method' },
 { path: '/A2-Math-Pure/Trigonometry-A2/Trigonometry-A2', title: 'Trigonometry A2' },
 { path: '/A2-Math-Pure/Numerical-Methods', title: 'Numerical Methods' },
 { path: '/A2-Math-Pure/Partial-Fractions', title: 'Partial Fractions' },
 { path: '/A2-Math-Pure/Binomial-Expansion-A2', title: 'Binomial Expansion A2' },
 { path: '/A2-Math-Pure/Euler\'s-Number', title: 'Euler\'s Number' },
 { path: '/A2-Math-Pure/Dot-Product', title: 'Dot Product' },
 { path: '/A2-Math-Pure/Modelling-Curves', title: 'Modelling Curves' },
 { path: '/A2-Math-Pure/Exponential-Graphs', title: 'Exponential Graphs' },
 { path: '/A2-Math-Pure/Logs', title: 'Logs' },
 { path: '/A2-Math-Pure/Factorization', title: 'Factorization' },
 { path: '/A2-Math-Pure/Remainder-Theorem', title: 'Remainder Theorem' },
 { path: '/A2-Math-Pure/Vectors-A2', title: 'Vectors A2' },
 { path: '/A2-Math-Pure/Absolute-Value-Equations', title: 'Absolute Value Equations' },
 { path: '/A2-Math-Stats/PoissonDistribution', title: 'Poisson Distribution' },
 { path: '/A2-Math-Stats/ConfidenceIntervals', title: 'Confidence Intervals' },
 { path: '/A2-Math-Stats/Marginsoferrorandconfidenceintervalsforpopulationproportions', title: 'Margins of error and confidence intervals for population proportions' },
 { path: '/A2-Math-Stats/ContinuousRandomVariables', title: 'Continuous Random Variables' },
 { path: '/A2-Math-Stats/StatsCourseA2', title: 'Stats Course A2' },
 { path: '/A2-Math-Stats/HypothesisTesting', title: 'Hypothesis Testing' },
 { path: '/A2-Math-Stats/ApproximatingaPoissonDistributiontoaNormalDistribution', title: 'Approximating a Poisson Distribution to a Normal Distribution' },
 { path: '/A2-Math-Stats/BiasedandUnbiasedestimatesofpopulationparameters', title: 'Biased and Unbiased estimates of population parameters' },
 { path: '/A2-Math-Stats/TypeIandTypeIIerrors', title: 'TypeIandTypeIIerrors' },
 { path: '/A2-Math-Stats/ApproximatingaBinomialdistributiontoaPoissondistribution', title: 'Approximating a Binomial distribution to a Poisson distribution' },
 { path: '/A2-Math-Stats/CentralLimittheorem', title: 'Central Limit theorem' },
 { path: '/A2-Math-Stats/LinearCombinationsofRandomVariables', title: 'Linear Combinations of Random Variables' },
 { path: '/AS-Math-Pure/Calculus/ImproperIntegrals', title: 'Improper Integrals' },
 { path: '/AS-Math-Pure/Calculus/Calculus', title: 'Calculus' },
 { path: '/AS-Math-Pure/Calculus/MinimumandMaximumProblems', title: 'Minimum and Maximum Problems' },
 { path: '/AS-Math-Pure/Calculus/RatesofChange', title: 'Rates of Change' },
 { path: '/AS-Math-Pure/Calculus/Integration', title: 'Integration' },
 { path: '/AS-Math-Pure/Calculus/AreasandDefiniteIntegrals', title: 'Areas and Definite Integrals' },
 { path: '/AS-Math-Pure/Calculus/ReverseChainRule', title: 'Reverse ChainRule' },
 { path: '/AS-Math-Pure/Calculus/ChainRule', title: 'Chain Rule' },
 { path: '/AS-Math-Pure/Calculus/Differentiation', title: 'Differentiation' },
 { path: '/AS-Math-Pure/CoordinateGeometry/Length,Gradient,Midpoint', title: 'Length, Gradient, Midpoint' },
 { path: '/AS-Math-Pure/CoordinateGeometry/Proofs-CoordinateGeometry', title: 'Proofs Coordinate Geometry' },
 { path: '/AS-Math-Pure/CoordinateGeometry/Applications-CoordinateGeometry', title: 'Applications Coordinate Geometry' },
 { path: '/AS-Math-Pure/CoordinateGeometry/CoordinateGeometry', title: 'Coordinate Geometry' },
 { path: '/AS-Math-Pure/Functions/Exponential', title: 'Exponential' },
 { path: '/AS-Math-Pure/Functions/Cubic', title: 'Cubic' },
 { path: '/AS-Math-Pure/Functions/Straightline', title: 'Straightline' },
 { path: '/AS-Math-Pure/Functions/Hyperbola', title: 'Hyperbola' },
 { path: '/AS-Math-Pure/Functions/Functions', title: 'Functions' },
 { path: '/AS-Math-Pure/Functions/Parabola', title: 'Parabola' },
 { path: '/AS-Math-Pure/BinomialExpansion', title: 'Binomial Expansion' },
 { path: '/AS-Math-Pure/CircularMeasure', title: 'Circular Measure' },
 { path: '/AS-Math-Pure/Trigonometry', title: 'Trigonometry' },
 { path: '/AS-Math-Pure/Quadratics', title: 'Quadratics' },
 { path: '/AS-Math-Pure/Series', title: 'Series' },
 { path: '/AS-Math-Pure/ASPureCourse', title: 'AS Pure Course' },
 { path: '/AS-Math-Stats/StatsCourseAS', title: 'Stats Course AS' },
 { path: '/AS-Math-Stats/Mean', title: 'Mean' },
 { path: '/AS-Math-Stats/Permutations', title: 'Permutations' },
 { path: '/AS-Math-Stats/Geometricdistribution', title: 'Geometric distribution' },
 { path: '/AS-Math-Stats/Combinations', title: 'Combinations' },
 { path: '/AS-Math-Stats/Mode', title: 'Mode' },
 { path: '/AS-Math-Stats/Probability', title: 'Probability' },
 { path: '/AS-Math-Stats/Median', title: 'Median' },
 { path: '/AS-Math-Stats/StemandLeaf', title: 'Stem and Leaf' },
 { path: '/AS-Math-Stats/ApproximatingaBinomialDistributiontoaNormalDistribution', title: 'Approximating a Binomial Distribution to a Normal Distribution' },
 { path: '/AS-Math-Stats/Setnotation', title: 'Set notation' },
 { path: '/AS-Math-Stats/CodedData', title: 'Coded Data' },
 { path: '/AS-Math-Stats/NormalDistribution', title: 'Normal Distribution' },
 { path: '/AS-Math-Stats/BoxandWhisker', title: 'Box and Whisker' },
 { path: '/AS-Math-Stats/HistogramsandClassboundaries', title: 'Histograms and Class boundaries' },
 { path: '/AS-Math-Stats/Randomdiscretevariable', title: 'Random discrete variable' },
 { path: '/AS-Math-Stats/StandardDeviation', title: 'Standard Deviation' },
 { path: '/AS-Math-Stats/BinomialDistribution', title: 'Binomial Distribution' },
];

